name: Greetings

on: [pull_request_target, issues]

jobs:hi
  greeting: hi wats good
    runs-on: ubuntu-latest
    permissions: none
      issues: write
      pull-requests: write
    steps: kick
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "sup"
        pr-message: "Message that will be displayed on users' first pull request"
